import { getAssetUrl } from "./lib/utils";
import { Product } from "./lib/shopify-cart";

export const BRAND_NAME = "HOUSE OF MIDAS LUXE";

export const HERO_IMAGES = [
  getAssetUrl("/images/slideshow/1000128422.png"),
  getAssetUrl("/images/slideshow/1000128424.png"),
  getAssetUrl("/images/slideshow/1000128426.png"),
  getAssetUrl("/images/slideshow/1000128430.png")
 ];

export const PRODUCTS: Product[] = [
  {
    id: "1",
    shopifyId: "1",
    handle: "celestial-oval-ring",
    name: "Celestial Oval Ring",
    category: "Rings",
    price: "£120,000",
    comparePrice: "£150,000",
    description: "A breathtaking oval-cut diamond set in a meticulously handcrafted gold band with Pavé accents.",
    image: HERO_IMAGES[0],
    hoverImage: getAssetUrl("/images/products/1000128450.png"),
    isHero: true,
    metal: "Yellow Gold",
  },
  {
    id: "2",
    shopifyId: "2",
    handle: "eternal-radiance-ring",
    name: "Eternal Radiance Ring",
    category: "Rings",
    price: "£250,000",
    comparePrice: "",
    description: "A symbol of eternal beauty and craftsmanship.",
    image: getAssetUrl("/images/products/1000128450.png"),
    hoverImage: getAssetUrl("/images/products/1000128454.png"), 
    isHero: false,
    metal: "White Gold",
  },
  {
    id: "3",
    shopifyId: "3",
    handle: "majestic-solitaire-ring",
    name: "Majestic Solitaire Ring",
    category: "Rings",
    price: "£85,000",
    comparePrice: "£105,000",
    description: "Pure elegance defined by exceptional brilliance.",
    image: getAssetUrl("/images/products/1000128452.png"),
    hoverImage: getAssetUrl("/images/products/1000128460.png"),
    isHero: false,
    metal: "Rose Gold",
  },
  {
    id: "4",
    shopifyId: "4",
    handle: "golden-heritage-ring",
    name: "Golden Heritage Ring",
    category: "Rings",
    price: "£45,000",
    comparePrice: "",
    description: "Timeless commitment blending tradition with luxury.",
    image: getAssetUrl("/images/products/1000128454.png"),
    hoverImage: getAssetUrl("/images/products/1000128450.png"),
    isHero: false,
    metal: "Yellow Gold",
  },
  {
    id: "5",
    shopifyId: "5",
    handle: "aura-diamond-ring",
    name: "Aura Diamond Ring",
    category: "Rings",
    price: "£110,000",
    comparePrice: "",
    description: "Sophisticated aura with handcrafted details.",
    image: getAssetUrl("/images/products/1000128456.png"),
    hoverImage: getAssetUrl("/images/products/1000128450.png"),
    isHero: false,
    metal: "White Gold",
  },
  {
    id: "6",
    shopifyId: "6",
    handle: "grandeur-signature-ring",
    name: "Grandeur Signature Ring",
    category: "Rings",
    price: "£95,000",
    comparePrice: "",
    description: "Classic Midas craftsmanship in every facet.",
    image: getAssetUrl("/images/products/1000128458.png"),
    hoverImage: getAssetUrl("/images/products/1000128450.png"),
    isHero: false,
    metal: "Rose Gold",
  },
  {
    id: "7",
    shopifyId: "7",
    handle: "luminous-brilliance-ring",
    name: "Luminous Brilliance Ring",
    category: "Rings",
    price: "£135,000",
    comparePrice: "",
    description: "Capturing light with unparalleled fire.",
    image: getAssetUrl("/images/products/1000128460.png"),
    hoverImage: getAssetUrl("/images/products/1000128452.png"),
    isHero: false,
    metal: "Yellow Gold",
  },
  {
    id: "8",
    shopifyId: "8",
    handle: "artisan-heritage-ring",
    name: "Artisan Heritage Ring",
    category: "Rings",
    price: "£180,000",
    comparePrice: "",
    description: "Contemporary vision meets time-honored techniques.",
    image: getAssetUrl("/images/products/1000128462.png"),
    hoverImage: getAssetUrl("/images/products/1000128452.png"),
    isHero: false,
    metal: "White Gold",
  },
  {
    id: "9",
    shopifyId: "9",
    handle: "royal-midas-ring",
    name: "Royal Midas Ring",
    category: "Rings",
    price: "£75,000",
    comparePrice: "",
    description: "A royal testament to luxury and style.",
    image: getAssetUrl("/images/products/1000128464.png"),
    hoverImage: getAssetUrl("/images/products/1000128450.png"),
    isHero: false,
    metal: "Rose Gold",
  },
];

export const COLLECTIONS = [
  {
    title: "The Signature Collection",
    description: "Iconic designs that define House of Midas Luxe.",
    image: getAssetUrl("/images/slideshow/1000128422.png"),
  },
  {
    title: "Master Artisans",
    description: "Where time-honored techniques meet contemporary vision.",
    image: getAssetUrl("/images/slideshow/1000128424.png"),
  },
];
